# example netlify.toml
[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "web/dist"

[dev]
  framework = "vite"

[[edge_functions]]
  path = "/workflows"
  function = "workflows"
